### ISSUE TITLE
Issue with cypress 3.4.0 version

### ISSUE THREAD

**Issue by kevinccbsg** [bahmutov/cypress-dark#128]
## BUG

There is an issue with this plugin when you try to install it for cypress versions newer than 3.2.0 and it is related to this Issue cypress-io/cypress#4352

- version: 3.4.0
- platform: MAC
- Run cypress dark mode
- An error like the image below

![Screen Shot 2019-08-21 at 12 11 23](https://user-images.githubusercontent.com/12685053/63424209-3936f500-c40e-11e9-8f21-2a8a766daa98.png)

## How to reproduce

Install the latest version of cypress and try to run cypress dark it will give you the screenshot error.

**Comment by kevinccbsg** [comment]
I added a solution in a PR https://github.com/bahmutov/cypress-dark/pull/127 
However, the CI pipeline went wrong 😞 🤔

**Comment by bahmutov** [comment]
I have fixed the pipeline and released new version, thank you @kevinccbsg
