### ISSUE TITLE
Doesn't work if cypress folder is not sibling of node_modules directory

### ISSUE THREAD

**Issue by jonstone904** [bahmutov/cypress-dark#160]
Using Cypress 3.6.1

My cypress directory is nested and is not a sibling of the node_modules folder so it is failing to load the dark theme

Example:
- Repo
     - node_modules
     - tests
          - master
               - cypress

![image](https://user-images.githubusercontent.com/46907262/69549869-0ef25780-0f68-11ea-85c3-c387eac4a9cb.png)

**Comment by seyfer** [comment]
I have the same issue now
![image](https://user-images.githubusercontent.com/1483925/71353733-401b7300-257a-11ea-99fd-928f7ba03f2c.png)

**Comment by jonstone904** [comment]
This appears to be working now actually so closing this issue
