### ISSUE TITLE
cypress-dark does not work with yarn

### ISSUE THREAD

**Issue by wlsf82** [bahmutov/cypress-dark#23]
## Is this a bug report or a feature request?
Bug

If this is a bug report, please provide as much info as possible

- version: 1.5.1
- Node.js version: 8.12.0
- platform: Unix (Mac OS High Sierra)
- expected behavior - being able to install cypress-dark using yarn, as I can do using npm.
- actual behavior - error when trying to install cypress-dark using yarn (see below).

```
$ yarn add cypress-dark --dev
yarn add v1.9.4
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
error cypress-dark@1.5.1: The engine "node" is incompatible with this module. Expected version "10.11.0".
error Found incompatible module
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
```

Note: I've tried in two different projects and got the exact same behavior.

**Comment by wlsf82** [comment]
What do I need to do make it work with TypeScript?

**Comment by bahmutov** [comment]
Does it not work with Typescript by default?

**Comment by bahmutov** [comment]
Yup, you probably need dev dependency`@types/node` to make sure require work - or even simpler just before `require` line use `// @ts-ignore` directive

**Comment by wlsf82** [comment]
By using `// @ts-ignore` I can use require, but the styling is still not applied :(
I'll investigate more tomorrow.

**Comment by bahmutov** [comment]
Yeah if you can make tiny reproducible example I can take a look

**Comment by wlsf82** [comment]
Does it matter if my test files have `.tsx` extension instead of `.ts`?
We decided to use the same extension for all files in the project (including test files) to keep a standard; even if I don't consider such an approach necessary.

By changing the `support` and `commands` file to `.js` and leaving the test files as `.tsx` made it work.
